[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
strict = true
warn_unused_ignores = true
warn_return_any = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
show_error_codes = true

[tool.pylint.main]
load-plugins = ["pylint.extensions.docparams"]

[tool.pylint.messages_control]
disable = ["missing-docstring", "invalid-name", "too-few-public-methods"]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.typecheck]
ignored-modules = ["winreg"]

[tool.pylint.reports]
output-format = "colorized"